### PR TITLE
TASK: Apply core migrations

### PR DESCRIPTION
**Pull request by gerhard-boden**

### CODE REVIEW

**Comment by daniellienert** [comment]
I guess we should tag / release the package before merging this?

**Comment by daniellienert** [comment]
@gerhard-boden: After merging 1.1 into master, we have some merge conflicts. Would you please solve them?

**Comment by gerhard-boden** [comment]
@daniellienert thanks for checking, conflict resolved

**Comment by baschny** [comment]
@daniellienert Post review:

I had this in my composer.json:
```
...
        "typo3/neos": "~2.2.0",
        "flowpack/elasticsearch": "dev-master",
...
```

We were using dev-master due to the introduced compatibility with ES 2.x, thus we cannot go back on using flowpack/elasticsearch 1.1.x.

This PR now broke our installation, because you switched from:
```
 -        "typo3/flow": "~2.3|~3.0"
 +        "neos/flow": "~4.0 | dev-master"
```

Since there is not a release from dev-master before this update of requirement, how should we proceed?

My suggestion is to make a release out of the version previous to this PR and tag it with "1.2.0" (for example) - the last version compatible with Neos 2.3 and Flow 3.3.

@kdambekalns what do you think?

**Comment by baschny** [comment]
I guess I was not entirely correct with my last comment. I have no problem with 1.1.x of `flowpack/elasticsearch`, but by problem comes from https://github.com/Flowpack/Flowpack.ElasticSearch.ContentRepositoryAdaptor/pull/162. See comment there.

**Pull request merged**
