### PR TITLE
TASK: Modify to work with Elasticsearch 7

### PR DESCRIPTION
**Pull request by DrillSergeant**
I changed the code to support Elasticsearch version 7 for custom domain model indexing. 

It will then no longer work with elasticsearch 5 because the API changed from ES version 5 to 6 why I introduced these changes:

- `\Flowpack\ElasticSearch\Domain\Model\AbstractType::findDocumentById` will use the path "_doc" to find documents
- `\Flowpack\ElasticSearch\Domain\Model\Document::store` will use the path "_doc" store documents to the index

### CODE REVIEW

**Review by daniellienert — APPROVED** [review]
The changes made make sense by reading. Current code parts are definitely not working.
Don't know if there are other missing parts. Honestly I don't use bare model indexing in any project but I know people are successfully using it.

**Comment by daniellienert** [comment]
@DrillSergeant, you should remove the compatibility to ES 5 in the readme.

**Comment by DrillSergeant** [comment]
@daniellienert thanks for the readme advice, I just did it.

Whoever is releasing this, I think the version number should reflect this is a breaking change.

**Comment by DrillSergeant** [comment]
Any chance for merge and release for this?

**Pull request merged**
